; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30136.0 

	TITLE	C:\Users\viraj\source\repos\Intel_sample_code\XsaveProject\Debug\FP_loop_test.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?init@@3MA					; init
msvcjmc	SEGMENT
__CBC66B61_FP_loop_test@cpp DB 01H
msvcjmc	ENDS
_DATA	SEGMENT
?init@@3MA DD	03f800000r			; 1	; init
_DATA	ENDS
PUBLIC	?_run_fpu@@YAMXZ					; run_fpu
PUBLIC	__JustMyCode_Default
PUBLIC	__real@3e648e8a
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__fltused:DWORD
;	COMDAT __real@3e648e8a
CONST	SEGMENT
__real@3e648e8a DD 03e648e8ar			; 0.2232
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
;__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
;__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\viraj\source\repos\Intel_sample_code\XsaveProject\FP_loop_test.cpp
;	COMDAT ?_run_fpu@@YAMXZ
_TEXT	SEGMENT
?_run_fpu@@YAMXZ PROC					;_run_fpu, COMDAT

; 3    : float _run_fpu() {

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	mov	edi, ebp
	xor	ecx, ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __CBC66B61_FP_loop_test@cpp
	call	@__CheckForDebuggerJustMyCode@4

; 4    : 	init = (0.2232f * init) + init;

	movss	xmm0, DWORD PTR __real@3e648e8a
	mulss	xmm0, DWORD PTR ?init@@3MA
	addss	xmm0, DWORD PTR ?init@@3MA
	movss	DWORD PTR ?init@@3MA, xmm0

; 5    : 	return init;

	fld	DWORD PTR ?init@@3MA			; init

; 6    : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?_run_fpu@@YAMXZ ENDP					;_run_fpu
_TEXT	ENDS
END
